steps:
  #
  # 1. 打包程式
  #
  - id: 'package-app'
    name: 'rockylinux:9'
    entrypoint: bash
    args:
      - -c
      - |
        tar zcvf ${TAG_NAME}.tar.gz \
          app.js \
          package-lock.json \
          package.json

  #
  # 2. 上傳到 bucket
  #
  - id: 'upload-app'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'storage'
      - 'cp'
      - '${TAG_NAME}.tar.gz'
      - 'gs://g-deploy/${REPO_NAME}'

  #
  # 3. 更新 _API 預設值
  #
  - id: 'update-deploy-substitutions'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta builds triggers export 00-05-create-instance-template \
          --region=asia-east1 \
          --destination=settings.yaml
        
        sed -i "s/_API: .*/_API: ${TAG_NAME}/g" settings.yaml

        gcloud beta builds triggers import \
          --source=settings.yaml \
          --region=asia-east1

options:
  logging: CLOUD_LOGGING_ONLY