steps:
  #
  # 1. 打包程式
  #
  - id: 'package-app'
    name: 'rockylinux:9'
    entrypoint: bash
    args:
      - -c
      - |
        tar -I pigz -cf release.tar.gz \
            01_bo/ \
            02_intg/ \
            03_api/ \
            04_ag/ \
            05_gc/ \
            package.json

  #
  # 2. 上傳到 VM
  #
  - id: 'upload-app'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute scp \
          --zone=asia-east1-b \
          --tunnel-through-iap \
          release.tar.gz \
          node-app-01:/tmp/release.tar.gz

  #
  # 3. VM 部署
  #
  - id: 'deploy-app'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh node-app-01 \
          --zone=asia-east1-b \
          --tunnel-through-iap \
          --command="
            sudo rm -rf /opt/app/cicd-test &&
            sudo mkdir -p /opt/app/cicd-test &&

            sudo tar xzf /tmp/release.tar.gz \
              -C /opt/app/cicd-test &&

            sudo chown -R deploy:deploy \
              /opt/app/cicd-test &&

            sudo systemctl restart node-bg &&
            sudo systemctl restart node-intg
          "

options:
  logging: CLOUD_LOGGING_ONLY