steps:
  #
  # 1. 打包程式
  #
  - id: 'package-app'
    name: 'rockylinux:9'
    entrypoint: bash
    args:
      - -c
      - |
        tar zcvf ${TAG_NAME}.tar.gz \
          app.js \
          package-lock.json \
          package.json

  #
  # 2. 上傳到 bucket
  #
  - id: 'upload-app'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'storage'
      - 'cp'
      - '${TAG_NAME}.tar.gz'
      - 'gs://g-deploy/${REPO_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY